### ISSUE TITLE
Use destructive-action for the red "Empty the trash" button

### ISSUE THREAD

**Issue by donadigo** [bcedu/VGrive#10]
Currently, the "empty the trash" button uses a custom `redbutton` class. Instead it could use a built-in `destructive-action` class and be consistent with the rest of the "red" buttons that are present in other apps. You can do it like so:
```
empty_trash.get_style_context().add_class (Gtk.STYLE_CLASS_DESTRUCTIVE_ACTION);
```

**Comment by bcedu** [comment]
Nice! I didn't know the built-in class 👍🏻
