### ISSUE TITLE
After a minute or so of running it closes itself

### ISSUE THREAD

**Issue by ezeveliz** [bcedu/VGrive#12]

**Comment by bcedu** [comment]
can you start it from the terminal with `com.github.bcedu.vgrive` and show the error message that appears when the app is closed?

**Comment by ezeveliz** [comment]
[log2.txt](https://github.com/bcedu/VGrive/files/3700764/log2.txt)

**Comment by bcedu** [comment]
I think it closes itself only when is running in background, if the app is not closed it works well. I'm working on the fix.

**Comment by ezeveliz** [comment]
Mmm, it wasn't closed, it was in the foreground

**Comment by bcedu** [comment]
I see that the app was closed when it was trying to download the file "fx-7400GPLUS_Sp_Ch02_ES.pdf". Does the app stops every time al this file?

Also, could you give me some specs about the machine where it is running? (model, SO, ...)

Thanks!

**Comment by bcedu** [comment]
Have you tryed if it works with the lastest release?

**Comment by ezeveliz** [comment]
Yes, sorry, it wouldn't close it self anymore.
