### ISSUE TITLE
when i closed Vdrive app whats hapen?

### ISSUE THREAD

**Issue by paulo8448** [bcedu/VGrive#14]
sorry if here is no place to make a question
But.
when a close VGrive app, the same app enter and second plan or just stop everything and close ?

**Comment by bcedu** [comment]
If it is syncing enters on second plan. If it is not syncing it is closed

**Comment by paulo8448** [comment]
Sorry man
my system did not warn me when I closed the application
when i restarted the system i received a notification answering my question
thank's for your help
and sorry again
