### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by erysonhandel** [bcedu/VGrive#15]
when i click to give access to VGrive 
it redirect me to google sign in page 
when i sign in i get error

Sign in with Google temporarily disabled for this app

This app has not been verified yet by Google in order to use Google Sign In.

![Screenshot from 2019-10-09 20 40 19](https://user-images.githubusercontent.com/56357167/66494298-0d162700-ead5-11e9-8ea2-8f97aa995d4f.jpeg)

**Comment by bcedu** [comment]
Yesterday google send me an email telling that i must verify my app. I did it but it will take some days until they accept the app. So we can only wait 🤷🏻‍♂️

**Comment by erysonhandel** [comment]
Thanks for speedy reply

**Comment by bcedu** [comment]
The app has been verified by google. You shouldnt have any problem to log in
