### ISSUE TITLE
Typo in word 'access'

### ISSUE THREAD

**Issue by zejji** [bcedu/VGrive#16]
Just a very minor issue, but easy to fix ;-)

Each instance of the word 'access' in English is mispelled as 'acces' (i.e. "Give acces to VGrive" and "Error trying to get acces token").

Correct spellings would be "Give access to VGrive" and "Error trying to get access token".

**Comment by bcedu** [comment]
Ups 🙈
It's obious that englishbis not my native language... 
Thanks for the issue, I will fix it!

**Comment by bcedu** [comment]
Closed by 11aec95d3d91e2695e353ad10cae5cac4ad86f69
