### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by yochananmarqos** [bcedu/VGrive#21]
I'm using Adwaita-maia-dark on Manjaro GNOME and some text is unreadable.

![Screenshot from 2019-10-28 10-51-24](https://user-images.githubusercontent.com/5437803/67699062-217d6f00-f971-11e9-8dde-bb12b4221ba0.png)

**Comment by bcedu** [comment]
Closed by 91713126442ad578c70b8a209fab92d38dfff4dd

It will be aviable in the next release

**Comment by bcedu** [comment]
![Captura de pantalla del 2019-10-31 21 25 33](https://user-images.githubusercontent.com/25721962/67983445-ff137c00-fc24-11e9-92d1-e9b052ee12ad.png)
