### ISSUE TITLE
Install from .deb file

### ISSUE THREAD

**Issue by nullproblemo** [bcedu/VGrive#28]
> For debian based distributions (ubuntu, linux mint, elementary, ...) you can install VGrive directlly with the .deb file attached to the newest release of VGrive.

Where can I find this .deb file?

**Comment by nullproblemo** [comment]
Thanks for your answer!

**Comment by nullproblemo** [comment]
```
Vormals nicht ausgewähltes Paket com.github.bcedu.vgrive wird gewählt.
(Lese Datenbank ... 391291 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von com.github.bcedu.vgrive_1.0_amd64.deb ...
Entpacken von com.github.bcedu.vgrive (1.0) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von com.github.bcedu.vgrive:
 com.github.bcedu.vgrive hängt ab von libgranite5 (>= 0.2.0); aber:
  Paket libgranite5 ist nicht installiert.
 com.github.bcedu.vgrive hängt ab von libunity9 (>= 3.4.6); aber:
  Paket libunity9 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes com.github.bcedu.vgrive (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für gnome-menus (3.31.4-3) werden verarbeitet ...
Trigger für desktop-file-utils (0.23-4) werden verarbeitet ...
Trigger für mime-support (3.62) werden verarbeitet ...
Trigger für libglib2.0-0:i386 (2.58.3-2+deb10u1) werden verarbeitet ...
Trigger für libglib2.0-0:amd64 (2.58.3-2+deb10u1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 com.github.bcedu.vgrive
```

Debian 10: libgranite5 is integrated. libunity9 isn't provided. So the installation fails.

**Comment by bcedu** [comment]
In the new version that will be released in the next days (when i had some free time) the unity supory will be optional:

https://github.com/bcedu/VGrive/commit/3f718d09f236c43a1e54fb66a740a479755b3ed0

This will allow install the app in OS whthout libunity

**Comment by nullproblemo** [comment]
Thanks, I stay tuned.

**Comment by nullproblemo** [comment]
Version 1.1.0: 

> Make unity support optional (by @dguglielmi)

I found a new file called _com.github.bcedu.vgrive_1.1.0_amd64.deb_. Trying to install it via dpkg -i or GDebi Debian 10 still requests _libunity9_. What can I do?

**Comment by bcedu** [comment]
This deb file still requires unity.
Im testing a new deb file where ive removed the libunity dependency and moved to "Reccomended". I will tell you when it's finished

**Comment by nullproblemo** [comment]
Great. Thanks!

**Comment by bcedu** [comment]
Hi! You will find a new `.deb` file attached to the las release: https://github.com/bcedu/VGrive/releases/tag/1.2.1

I've tested it in a debian without unity and it worked well.

**Comment by nullproblemo** [comment]
I confirm that. It works well with XFCE!
