### ISSUE TITLE
Icons not showing inside VGrive

### ISSUE THREAD

**Issue by JediFonseca** [bcedu/VGrive#29]
I've just manually installed VGrive on Fedora 31 by following the instructions here on Github. The software installed and opens properly, but the icons are not showing when I open it. Check it out:

![Captura de tela de 2019-10-30 17-27-26](https://user-images.githubusercontent.com/47907146/67896328-e7f85f80-fb3a-11e9-9601-c2459b513c5a.png)

![Captura de tela de 2019-10-30 17-27-31](https://user-images.githubusercontent.com/47907146/67896344-f0509a80-fb3a-11e9-982d-b653cb2a15db.png)

**Comment by bcedu** [comment]
Actually the app is designed for debian based distros. I don't know if this could be the problem, althrought the icons managment should be the same in fedora... (but I've never worked with non debian distros).
Maybe It would be better to wait until I finish the flatpak and install it from there.

**Comment by kzoli429** [comment]
Running Arch Linux, I second to JediFonseca. I have installed it from AUR. I do not think flatpak would bring a common solution to distros other than debian. Very big Thank You if you could consider other distros.

**Comment by bcedu** [comment]
I use built-in icons like `pager-checked-symbolic`. The app has been developed in elementaryos. I really don't know if this icons only exist in elementaryos, in ubuntu based or in debian based.

But with flatpak, you choose a base OS, and as I will choose elementaryos this icons should be aviable. 

I also will try to check from the app  if the icons exist and use other icons if they doesnt exist, but ive never done it before so I dont know how do i have to do it.

**Comment by kzoli429** [comment]
Unfortunately, pager-checked-symbolic icon theme is non existent in Arch Linux and it cannot even be installed as a dependency. Maybe simply using text 1 2 3 for setup steps?

**Comment by bcedu** [comment]
I will try it and see how it looks.

I will also try to change the icon form the initial screen. I use the granite component "Welcome" :

https://valadoc.org/granite/Granite.Widgets.Welcome.html

I dont know which icon uses by default but it looks like its not aviable in arch linux.

**Comment by kzoli429** [comment]
https://wiki.archlinux.org/index.php/Arch_terminology#KISS
"
KISS
Acronym of Keep It Simple, Stupid. Simplicity is a main principle Arch Linux tries to achieve.
"
Thanks in advance for your efforts.

**Comment by bcedu** [comment]
Check out the new release:

https://github.com/bcedu/VGrive/releases/tag/1.2.3

I use other icons that should be aviable in other distros. I've tested in fedora and debian.

**Comment by kzoli429** [comment]
In order to run a clean setup again I need to delete the app including the config file too. Can I have its location/path?

**Comment by bcedu** [comment]
All the conf files are places inside the Synced Folder (by default: /home/username/VGrive).

The conf file is named  
`.vgrive_library`. The trash folder is named `.trash`.

**Comment by kzoli429** [comment]
For some reason I cannot do a clean installation. After removing the app and config file as well, restart then install it always continues syncing instead of new setup. I carry on trying.
Anyway just as a tip a trick, I wonder if there may be a way to start vgrive from terminal; for example
- a for Advanced View
- m for starting it minimized after boot
- v to check version number
It would be useful for certain Desktop Environments; i.e. XFCE, where app icon could be pinned to panel. (It seems that XFCE panel plugin has not been designed and this way it could partly be replaced by pinning it for quick open/close/operational check.)

**Comment by bcedu** [comment]
My fault, you still need to delete the credentials file. Thats why the app continues syncing. The credentials file is `/home/username/.vgrive/credentials.json`.

Althrough you dont need to delete this file to go back to initial state, you can go to the config menu and use the button "Log out".

About starting vgrive from terminal, I will do it in the future bht by now it cant be done. Feel free to open a new issue requesting it.

**Comment by kzoli429** [comment]
vgrive 1.2.3-1 installed. Now icons are all right. Nice job.

Notes:
1. When Preferences are invoked (Actions screen) the only option is to Save or close window, I miss a Cancel button to return to the opening screen.
2. For me it would be reasonable to start app after boot with Advanced View checked (maybe the same note as the request for command option; i.e. -a)

Just a few typing errors:
"Syncing stoped by user request" -> stopped
"NEW REMOTE FILE: <file> downloding..." -> downloading

I hope I could help with debugging.

**Comment by bcedu** [comment]
New issues :  
https://github.com/bcedu/VGrive/issues/37
https://github.com/bcedu/VGrive/issues/36

**Comment by JediFonseca** [comment]
Due to personal reasons I couldn't be here during all the debugging process, but I've just made a clean install, and It's working great! The icons are showing the way it should on Fedora 31, and now the Dark Mode is working fine. Including the dark mode switch. Good job! I'm a writer for [**Diolinux**](https://www.diolinux.com.br/), a brazilian website about Linux & Tech, and now I'm gonna be testing VGrive for a few days, and then I'll write a review about it. Thank you for the fast solution, and keep up with the good work!

**Comment by Timbo66** [comment]
I am using vgrive on fedora 31
when it opens there is no menu etc just a full screen with no options except advanced view
how do you access the menu

**Comment by bcedu** [comment]
Please, dont make comments on closed issues. 

Open a new issue with your problem/request.
Also make sure you are using the newest version of vgrive installed.

Thanks!
