### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by jschoedt** [bcedu/VGrive#31]
Hi,

I am having issues reading the text on Elementary OS. I think its because I am using dark mode? Im not sure but its not an issue in other apps.

Thanks for a nice app :-)

![image](https://user-images.githubusercontent.com/11059100/68019774-f2326f00-fc9c-11e9-83f2-eb920b674b20.png)

**Comment by bcedu** [comment]
Its already solved:

https://github.com/bcedu/VGrive/issues/21

The nex release will have dark mode suport
