### ISSUE TITLE
Installation support

### ISSUE THREAD

**Issue by antonio-petricca** [bcedu/VGrive#32]
Hi, when a SNAP or APT package?

Thank you so much!

**Comment by bcedu** [comment]
There will not be neither snap nor apt package by now.

But I've just attached a `.deb` file to the last release ( https://github.com/bcedu/VGrive/releases/tag/1.2.1 ) and I'm in process to publish a flatpak in the flathub (see https://github.com/bcedu/VGrive/issues/27).
