### ISSUE TITLE
Start vgrive minimized and other options

### ISSUE THREAD

**Issue by kzoli429** [bcedu/VGrive#35]
It would be useful if vgrive could be started from terminal with additional options; for example
    - a for Advanced View
    - m for starting it minimized
    - v to check version number
It would be advantageous for certain Desktop Environments; i.e. XFCE, where app icon can be pinned to panel. (It seems that XFCE panel plugin has not been designed and this way it could partly be replaced by pinning app for quick open/close/operational check.)

**Comment by bcedu** [comment]
Closed with 8f8c75f558468641c053850f9cffb087a1d7afe2
