### ISSUE TITLE
VGrive corrupts GoogleDocs and Google Spreadsheet files

### ISSUE THREAD

**Issue by axel22** [bcedu/VGrive#47]
This is pretty serious. Some of my google docs files are getting randomly corrupted (luckily not all of them).
See screenshots.

![screenshot-10-11-52](https://user-images.githubusercontent.com/151774/68284490-eddfca80-007d-11ea-8fb1-ed97837dc147.png)

![screenshot-10-11-12](https://user-images.githubusercontent.com/151774/68284496-efa98e00-007d-11ea-8a38-49970a3001af.png)

Luckily, there were only ~20-30 documents that were corrupted, and I was able to restore these files from the version history.
As far as I can tell, only googledoc files are affected, since the API apparently does not allow downloading their source.
Still, this should be fixed, and I turned off VGrive for the time being.

How could this be happening? Why does VGrive push files that were not changed locally.

**Comment by bcedu** [comment]
Any google doc should have been ignored by vgrive. I will check and fix it

**Comment by axel22** [comment]
Could it be that some local program/service "touches" those googledoc files, which tricks VGrive into thinking that they were changed, and into pushing the local copies back (which do not contain the true contents of those googledoc files, since they were never properly downloaded to begin with).

**Comment by bcedu** [comment]
Fixed with: 5e8fdb6d2c084d851f0b0a46355652b8c13314cf

I will make a new release with this fix.

Apologies for any inconvenience

**Comment by bcedu** [comment]
https://github.com/bcedu/VGrive/releases/tag/1.2.4

**Comment by axel22** [comment]
Thanks for fixing this!

**Comment by fyodorovski** [comment]
It's more than that - vGrive permanently deleted some files for me. See screenshot.

![screenshot-22-51-46](https://user-images.githubusercontent.com/21124449/68513218-c013a500-027a-11ea-8eec-7d1919cecc21.png)

I have no way of getting these files back!

**Comment by bcedu** [comment]
In v1.2.4 trying to fix this issue i introduced a bug that could cause this behaviour. It has been solved in v1.3.0

**Comment by bcedu** [comment]
Have you checked if this files are im the trash directory of VGrive?

Apologies for any inconvemience
