### ISSUE TITLE
Error: Dependency is not satisfiable: libgranite5 (>=5.2.3)

### ISSUE THREAD

**Issue by Gonm1** [bcedu/VGrive#60]
Trying to install from com.github.bcedu.vgrive_1.3.0_amd64.deb file, but getting dependency error. I am using Linux Mint 19.2

> Error: Dependency is not satisfiable: libgranite5 (>=5.2.3)

Edit: fix typo.

**Comment by bcedu** [comment]
The dependency should be `libgranite5 (>= 5.2.3)`, not `libfranite5`. Tested with the deb file attached to the 1.3.0 release:

![d1](https://user-images.githubusercontent.com/25721962/69434949-f05d4800-0d3e-11ea-940f-82bfb720a56d.png)

What do you get with the command `dpkg -I com.github.bcedu.vgrive_1.3.0_amd64.deb`?

**Comment by Gonm1** [comment]
It was a typo. This is the output of  **dpkg -I com.github.bcedu.vgrive_1.3.0_amd64.deb**

```
new Debian package, version 2.0.
 size 90228 bytes: control archive=1228 bytes.
     595 bytes,    10 lines      control              
    2446 bytes,    26 lines      md5sums              
 Package: com.github.bcedu.vgrive
 Version: 1.3.0
 Architecture: amd64
 Maintainer: Eduard Berloso Clarà <eduard.bc.95@gmail.com>
 Installed-Size: 1713
 Depends: dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.39.4), libgranite5 (>= 5.2.3), libgtk-3-0 (>= 3.21.4), libjson-glib-1.0-0 (>= 0.12.0), libsoup2.4-1 (>= 2.41.90)
 Section: x11
 Priority: extra
 Description: VGrive is a client (back-end and front-end) for Google Drive made in vala.
  Automaticlly detects changes in local and remote files and sync them.

```

**Comment by bcedu** [comment]
Then try to install manually `libgranite5` and you will se the problem. It's a public package, you can find it here: https://pkgs.org/download/libgranite5

**Comment by Gonm1** [comment]
The package can not be located by apt install libgranite5. And in the page there is no option for linux mint nor ubuntu 18.04.

**Comment by bcedu** [comment]
You can try installing the debian version, as linux mint is based on debian it should work.

**Comment by Gonm1** [comment]
I had to install
https://debian.pkgs.org/10/debian-main-amd64/libgranite5_5.2.3-1_amd64.deb.html
and then 
https://debian.pkgs.org/10/debian-main-amd64/libgranite5_5.2.3-1_amd64.deb.html
to use the .deb file for VGrive.
Thanks for the support.
