### ISSUE TITLE
Support for Google documents?

### ISSUE THREAD

**Issue by Doc73** [bcedu/VGrive#61]
Dear Dev,
have you planned to add support for Google documents (gddoc, gdsheet and gdslides)?

Currently, these files are downloaded as such and reuploaded onto Drive, causing their duplication on the cloud.

Thank you so much in advance and best regards,
DC

**Comment by bcedu** [comment]
Hi! I have not planned to implement support for google drive docs as they can't be edited as regular files once they are downloaded. Also they have a different behaviour trhough the Google Drive API.

In the version 1.4.0 that was recently released **VGrive doesn't download google drive docs any more.**
