### ISSUE TITLE
Which folder to scan in Google Drive 

### ISSUE THREAD

**Issue by AmanAjayVarma** [bcedu/VGrive#63]
Now my whole Google Drive is downloaded but I just want a specific folder to sync. If we can choose which folder to sync in from Google Drive would be awesome. And also does this application runs in the background?

**Comment by bcedu** [comment]
Currently selecting folders to sync is not supported. There is an open issue about it https://github.com/bcedu/VGrive/issues/26

About the backround syncing: yes it runs on the backround. 

If you have libunity installed, when you close the app it shows a notification explaining it.

If you have libappindicator3 installed, there is an icon in the tray icon area indicating that vgrive is running.
