### ISSUE TITLE
Version 1.4.0 doesn't start

### ISSUE THREAD

**Issue by nullproblemo** [bcedu/VGrive#64]
Version 1.4.0 doesn't start anymore under Debian 10. It seems to be broken. I reinstalled version 1.3.0.
![1-4-0](https://user-images.githubusercontent.com/8386713/69895968-b2ad8000-1339-11ea-8687-12045f4f2d64.png)

**Comment by bcedu** [comment]
Did you have a problem during installation?
Was it once you opened the app?

**Comment by nullproblemo** [comment]
No, I didn't have any problems during installation.
Yes, it was once I opened the app: It didn't start. Version 1.3.0 still works fine.

**Comment by bcedu** [comment]
I'm working on a fix I've just found with the debian package: it expects libunity to be installed althrought it should be optional. Try to open the app through command line to see if this is the error that you get. Type `com.github.bcedu.vgrive` to start from command line.

**Comment by bcedu** [comment]
I've updatet the `.deb` file attached to the 1.4.0 release. If you uninstall vgrive and install it again with the new `deb` file it should work

**Comment by nullproblemo** [comment]
Now it starts without gui but working in the background by default. The gui appears when I start the programm again. Is this alright?
![1 4 0](https://user-images.githubusercontent.com/8386713/69900249-57977f80-1371-11ea-9e12-286c72813ab0.png)

**Comment by bcedu** [comment]
If you gobto the configuration, there is an option to choose if the apos starts in the background. Maybe you have it enabled

**Comment by nullproblemo** [comment]
Yes, that's it. Thanks!
