### ISSUE TITLE
Exclude files/directories from sync

### ISSUE THREAD

**Issue by x80486** [bcedu/VGrive#65]
I think it would be extremely useful to be able to filer/select which files/directories to exclude from syncing back to `Drive`.

Example of this are, for instance, those `.~lock.file_name.ods#` files that `LibreOffice` create when you edit a file that's in a location being synced. We don't really need those so it would be great if `VGrive` has a way to skip those.

Last but not least, thanks again for developing `VGrive` and make it open source :trophy:

**Comment by apsteinmetz** [comment]
Forgive me if this is obvious. The way GDrive works now, there is local client called "Backup and Sync." In the cloud there are separate storage areas, one for each computer you connect, called "Computers" and a common "My Drive"  You select which folders on your computer you want to keep synced. The folder names  are typically identical across multiple machines, "Pictures" "Documents" and so on, but the folders in the cloud are unique to each machine. Separately you might have a another local folder called "Google Drive" that is synced.  Using the desktop client you can select which subfolders in Google Drive you sync.  These go into the common area and will be shared across any number of devices similarly configured.  Some, all or none of the folders may be common to another machine.  If they have the same name they get shared across machines.  The is the section that VGrive connects to.

The issue with VGrive is there is no option to select specific subfolders.  As soon as I connected it started to slurp up every file in the "My Drive" section of Google Drive to my wee tiny Linux box.  Whoa! I just want to back up specific folders.

From a VGrive design perspective this could be either a sync to the "Computer" or the "My Drive" section, but the latter is a more general solution.

Thanks for your efforts!

**Comment by caguiar** [comment]
Also think that it would be extremely useful to be able to filer/select which files/directories to exclude from syncing back to Drive. Hoping that it gets implemented. Thank you.

**Comment by toxic0berliner** [comment]
I'd really like to have that feature too ;)

**Comment by arnishow** [comment]
Hi, any news on this?
Thanks

**Comment by bcedu** [comment]
Hi! Thanks for the interest!
I usually work on this project on holidays, so don't expect to have this done at least until september.

**Comment by JoKalliauer** [comment]
> Hi! Thanks for the interest!
> I usually work on this project on holidays, so don't expect to have this done at least until september.

Is there any update? Is it implemented/will it be implemented?
