### ISSUE TITLE
VGrive doesn't show tray icon in Cinammon

### ISSUE THREAD

**Issue by RudahXimenes** [bcedu/VGrive#71]
VGrive isn't showing any tray icon in Cinnamon (Linux Mint 19.3), although show a notification that is running in background.

However looks like it crashes and close without any prompt.

**Comment by bcedu** [comment]
The .deb version doesn't have support for tray icons. I'm planing to sumbit a `.deb` package with this behaviour, but by now you will have to install it manually if you want the tray icons
