### ISSUE TITLE
timeintervals for autosync

### ISSUE THREAD

**Issue by AlwaysOn24** [bcedu/VGrive#74]
I changed a file in google drive and looked, if lokal on my computer the change gets happen, but the change is still not synchronized. how long to wait, until it gets synchronized?
in the other direction, if I make a change on the local computer in the vgrive folder, how long does it take, until this change is beeing recognized and synced with google drive?

**Comment by bcedu** [comment]
It is supposed to check changes each 10 seconds. If you change to "Advanced view", which is the log vgrive is showing?

**Comment by AlwaysOn24** [comment]
10 seconds? i changed the content of a txt-file in the google server, but
the change was synced after over 30 minutes... haha, 10 seconds? really?

**Comment by bcedu** [comment]
>> over 30 minutes... haha, 10 seconds? really?
Ok, there is not reason to be rude. As i said "it is suposed to", ther can be a bug or some unexpected behaviour. That's the reason I asked you the log that vgrive was showing.

But if you only make sarcastic comments without giving the information I asked  in order to solve the problem, I can't do anything.

**Comment by AlwaysOn24** [comment]
sorry for not beeing neutral. to keep the balance I want to underline that
your program is a very good solution and your quick response shows me that
you are still on this project in improving the software. as I migrated to
insync beta I can not give you the logs anymore, sorry about that. but to
help you with further improving the software, I would recommend for some
kind of FAQ available and maybe you like to put some infobutton in the
running-programs-bar from where I can see what the program is doing
(syncing, idel, run in error, next sync scheduled in .. minutes). I know
its making it then a more comercial product, if you further let the user
specify what folders are beeing synced, so for now, just these little
improvements would just be fine, if you want to let the program freeware.
thank you for your quick response and GOD bless you.
