### ISSUE TITLE
Change Requested for AppCenter: advertising "tray icon"

### ISSUE THREAD

**Issue by cassidyjames** [bcedu/VGrive#76]
Thanks for submitting your latest release to AppCenter. We have reviewed the submission, and have one minor change we would like to request.

In your AppData, you advertise a "tray icon" feature. However, this is disabled on elementary OS, and thus your AppData is advertising a non-existent feature to users. Please remove references to this feature for users of elementary OS.

We look forward to your resubmission!

**Comment by bcedu** [comment]
@cassidyjames I know it is desabled in elementary OS by default, but it can be enabled (there are lots of posts about it https://elementaryos.stackexchange.com/questions/17452/how-to-display-system-tray-icons-in-elementary-os-juno). 

I've updated the appdata to explaint this feature is only aviable for users who have enabled it (https://github.com/bcedu/VGrive/commit/8c7ee5dacf674c97b076d6738946554628516faf). Is it enought?
