### ISSUE TITLE
impossibile to open file inside del folder

### ISSUE THREAD

**Issue by J0hnnyb0y86** [bcedu/VGrive#80]
i cant open any file in the folder, OS Elementary OS last version

**Comment by bcedu** [comment]
Does it show any error? Are the files corrupted?

**Comment by J0hnnyb0y86** [comment]
no a pdf file i haved open it on browser without problem, all files in drive is 1,1kb,

**Comment by J0hnnyb0y86** [comment]
update all file is signed as HTML i haved open one and 
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
See Google Help for more information.

**Comment by bcedu** [comment]
Looks like google drive has banned your ip...

**Comment by bcedu** [comment]
Dont know why

**Comment by bcedu** [comment]
Do you get the same error if you trybto download the same file from the internet browser?

**Comment by grevius5** [comment]
I have the same problem, maybe its because I have activated the 2-factor authentication. I can tell you that I can download all the files I need from the browser without problems.

**Comment by grevius5** [comment]
I have a problem now, I tried to log out and then log in again, but this happened:
`
Syncing stopped by user request
DELETE REMOTE FILE: file_name.jpg
...
Start syncing files on path_to_my_dir
`
now I have lost all my files on gdrive, I look in the trash but nothing is present, how can I recover my lost file, I need it for work...

**Comment by bcedu** [comment]
Have you lokked in the .trash directory that vgrive creates inside path_to_my_dir?

**Comment by grevius5** [comment]
yes, it's empty...

**Comment by bcedu** [comment]
Then it has been deleted, im sorry. In the newest verion Vgrive no longer removes files from Drive, they are moved to trasg, but in previous versions they are deleted

**Comment by grevius5** [comment]
nooo!!! but if I go in settings I can see the message: vGrive doesn't delete any file, they are moved to the ".trash" folder

**Comment by bcedu** [comment]
Thata why i told you to look in trash but if the trash folder is empty i cant do anything...

**Comment by caguiar** [comment]
I have the same issue. All files are HTML and have the following message:

We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
See Google Help for more information.

But can access any with the browser.

**Comment by bcedu** [comment]
I opened an issue to Google Drive about this problem: https://issuetracker.google.com/issues/153717392

I think they already fixed it, cause it's working again. You will need to install the lastest release of VGrive in order to make it work.

**Comment by caguiar** [comment]
I have VGrive version 1.5, installed with Flatpak.
I get the following message: Error found, process stoped. Error message: Google Drive Connection Error: google drive has blocked your IP, VGrive can't sync files while google drive continue blocking the IP...
However I can assure you that I can access GDrive through the browser, at any time.

**Comment by bcedu** [comment]
Newest version is 1.6. In version 1.5 when the google error is detected sync is stopped with that message.

As i said, google had a bug that i managed to fix in version 1.6.

**Comment by caguiar** [comment]
Ok, it seems that version 1.6 is not in Fluthub yet, so I will have to wait.
https://flathub.org/apps/details/com.github.bcedu.vgrive

**Comment by bcedu** [comment]
Ive already published it but I dont know how often they check it and put it on flathub

**Comment by caguiar** [comment]
Got it, and its working. Thank you.
