### ISSUE TITLE
Unable to install VGrive on KDE Neon via Flatpak

### ISSUE THREAD

**Issue by VladimirMikulic** [bcedu/VGrive#81]
![error](https://user-images.githubusercontent.com/35997844/77826822-155d2f80-7112-11ea-97c7-a49241d0d0e2.png)

**Desktop**
 - OS: KDE Neon 5.18
 - VGrive Version: 1.5.0 Flatpak

**Comment by bcedu** [comment]
Hi!
How did you installed it? I checked the flatpak version and worked for me (Elementary OS), I also tested in Linux Mint and Ubunto (I don't have any KDE VM currently). It should work, the main goal of flatpak is to be able to work in any OS...

Can you try to unisntall and install it again? Maybe there was some problem during installation.

**Comment by VladimirMikulic** [comment]
Alright, I got it working, but I apparently don't know much about flatpaks.
The command should be executed in the directory where the vGrive folder resides.

Anyway, thank you for your fast response!
