### ISSUE TITLE
Where do the files go

### ISSUE THREAD

**Issue by shtonchjo** [bcedu/VGrive#89]
I must have missed something, but I don't know where the files syncd by VGrive go on my Google Drive
Thanks

**Comment by Cing2** [comment]
In the my drive section. It syncs the whole drive if i am correct

**Comment by shtonchjo** [comment]
It seems to sync from my machine, but I don't know where in Google Drive : On Google Drive, I cannot find the files that were sync'd

**Comment by bcedu** [comment]
Files syncked are added to your main drive .

If you don't find the files in the computer  you can check the folder where they are downloaded from the config button:
![image](https://user-images.githubusercontent.com/25721962/84573181-26c3e880-ad9f-11ea-95e7-f8d4059dd860.png)
![image](https://user-images.githubusercontent.com/25721962/84573184-2b889c80-ad9f-11ea-9571-8fd88e5ad859.png)

**Comment by shtonchjo** [comment]
Thanks for the reply : so VGrive doesn't sync **to** Google Drive, but only
from Google Drive? Also, it "syncs" the whole content of Google Drive
(there is no way to indicate which folders to sync)?
 I thought it was both ways as sync let's me believed

Thank you
Kind regards
Pierre
