### ISSUE TITLE
App is not available in the AppCenter

### ISSUE THREAD

**Issue by kostyabakay** [bcedu/VGrive#9]
![image](https://user-images.githubusercontent.com/9611539/66257390-4a12ae80-e7a1-11e9-93a2-a2c10a4e7f1d.png)

**Comment by bcedu** [comment]
The app is still not published. It will work when the app have been published

**Comment by kostyabakay** [comment]
But I saw here several releases. Are they stable?

**Comment by bcedu** [comment]
Yes they are. Its not published on the app center because the elememtary team is testing it.

**Comment by kostyabakay** [comment]
If I install this app manually will it be possible to install the next app updates via AppCenter instead of the command line?

**Comment by bcedu** [comment]
You will have to uninstall it and then install it via appcenter if you want to get the updates via app center
