### ISSUE TITLE
Add Arch Version & Fix Icon Show

### ISSUE THREAD

**Issue by liberodark** [bcedu/VGrive#90]
Hi,

Here have version : 
[vgrive-1.6.0-1-x86_64.pkg.zip](https://github.com/bcedu/VGrive/files/4574776/vgrive-1.6.0-1-x86_64.pkg.zip)

And please fix the app on icon show bar is not visible on XFCE.

Best Regards & Good Work

**Comment by bcedu** [comment]
I will not add arch version, you can install vgrive to arch throgugh flatpak: https://flathub.org/apps/details/com.github.bcedu.vgrive

PD: the reason that I published vgrive to flathub is to aviod having to do a version for every linux distro.
